version: "3.4"

services:
  web:
    image: practicadocker:latest
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
